http:
  server:
    addr: ":7777"
    readTimeout: 10
    writeTimeout: 10
    readHeaderTimeout: 10
  client:
    timeout: 1

modem:
  host: "http://192.168.8.1"
  pathHome: "/html/home.html"
  pathReboot: "/api/device/control"
  pathToken: "/api/webserver/SesTokInfo"
  bodyReboot: "<request><Control>1</Control></request>"
  checkHost: "https://yandex.ru"

url:
  getIP: "https://myexternalip.com/raw"

bee:
  mode: "release"
  log: "file"

cache:
  defaultExpiration: 5
  cleanupInterval: 10